env: "local" # dev, prod, local
data_base:
  adress: "localhost:5432"
  user: "user"
  password: "password"
  name: "orders_db"
  ssl_mode: false
kafka:
  adress: "localhost:29092"
  group_id: "order-consumer-group"
  offset_reset: "earliest"
  topic: "orders"
http_server:
  adress: "localhost:8081"
  timeout: 10s
  idle_timeout: 60s